### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Nokorbis** [AlfredoRamos/phpbb-ext-simple-spoiler#2]
Hey there !

This is not an issue but I don't want to fork for only 4 lines :)
I just want to propose you a French (fr) translation for your extension. :)

```
$lang = array_merge($lang, [
	'SPOILER'			=> 'Spoiler',
	'SPOILER_HELPLINE'	=> 'Utilisation : [spoiler]texte[/spoiler] ou [spoiler=titre]texte[/spoiler]',
	'SPOILER_SHOW'		=> 'Afficher',
	'SPOILER_HIDE'		=> 'Cacher'
]);
```

I keep the word "Spoiler" as I don't think we have any other word for that expression.

**Comment by AlfredoRamos** [comment]
Thank you ;)

**Comment by Galixte** [comment]
Hi @Nokorbis : « Masquer » plutôt que « Cacher », car ce dernier est utilisé pour les objets non pour du texte.

**Comment by AlfredoRamos** [comment]
@Nokorbis @Galixte So... it needs to be changed?

PS: It would be great if you could speak in English, I had to use Google Translator :P

**Comment by Nokorbis** [comment]
@AlfredoRamos 
Galixte is proposing to change "_Cacher_" to "_Masquer_" for SPOILER_HIDE.
For me they are synonyms and as a native I've never really seen any difference between these two.
But according to [this post](http://french.stackexchange.com/questions/8006/what-is-the-difference-between-cacher-and-masquer) it may make sense to change to "_Masquer_" indeed.

**Comment by Galixte** [comment]
Hi @Nokorbis, thanks ! Moreover, the french translation from phpBB-fr.com uses this term. ;)

@AlfredoRamos “PS: It would be great if you could speak in English, I had to use Google Translator :P” It cannot hurt you to learn a few words in French :P
