### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by ConeRX** [AlfredoRamos/phpbb-ext-simple-spoiler#3]
Hi,
I did a german translation (_de_ and _de_x_sie_) of your extension for my forum. I thought you might wanna have it:
```
$lang = array_merge($lang, [
	'SPOILER'			=> 'Spoiler',
	'SPOILER_HELPLINE'	=> 'Verwendung: [spoiler]Text[/spoiler] oder [spoiler=title]Text[/spoiler]',
	'SPOILER_SHOW'		=> 'Anzeigen',
	'SPOILER_HIDE'		=> 'Ausblenden'
]);
```

**Comment by AlfredoRamos** [comment]
Thank you!

Currently the version 1.0.8 is under validation, so it will be included in the next version (>=1.0.9), however I will provide a download link in the [support section](https://www.phpbb.com/customise/db/extension/simple_spoiler_bbcode/support) of the extension, for those who are currently using it.
