### ISSUE TITLE
Broken with 3.1.7+

### ISSUE THREAD

**Issue by recon88** [AlfredoRamos/phpbb-ext-simple-spoiler#3]
I just installed the mod and am getting "500 (Internal Server Error)" on every single page I try to open.

**Comment by AlfredoRamos** [comment]
@recon88 Well, it's not a mod but an extension, so you don't need to edit any file, if you did that might be the problem.

Which version did you install? What's your PHP version?

**Comment by recon88** [comment]
I did not edit any files. Just installed it like any other extension.
Using the latest from Github (1.0.0). 
PHP Version 5.4.45-0+deb7u2

**Comment by AlfredoRamos** [comment]
Please check your Apache error log (`error_log`). Does it give you more info?

I can't reproduce the error in my test server, it also works as expected in phpBB 3.1.8

I'll have to compile that PHP version on my server to test (Arch only has php 5.6 and up), meanwhile please disable the extension, delete all the extension data and clear the cache. After that re-upload the extension, you can use this zip file, you only need to unzip and upload the `alfredoramos` directory in your `ext` path.

- [phpbb-ext-simple-spoiler-1.0.0.zip](https://github.com/AlfredoRamos/phpbb-ext-simple-spoiler/files/148516/phpbb-ext-simple-spoiler-1.0.0.zip)

**Comment by recon88** [comment]
I did check the error log before. Nothing about the issue in there.

That's what I did before with 1.0.0.... Just repeated the steps, same issue.

**Comment by AlfredoRamos** [comment]
I can't reproduce the error with php 5.4.45 either. I need more info to test:

- It's a official phpBB release or it's a beta/alpha/RC?
- What's your board style?
- What's your hosting service? Is it a free hosting?
- Did the extension work on your server with phpBB 3.1.6?

Other possibilities that come to my mind are file permissions and your server setup itself. It can be anything, it even may not be related with the extension.

**Comment by recon88** [comment]
* I'm on 3.1.7-pl1. Didn't see an update for phpBB was available. But I guess that doesn't change anything.
* I'm using a custom style
* Paid hosting
* Never used 3.1.6. Started with the version mentioned above.

**Comment by AlfredoRamos** [comment]
@recon88 Wha'ts the name of your style?

**Comment by recon88** [comment]
Quarto Asphalt (paid style)

**Comment by AlfredoRamos** [comment]
I tried almost everything and still can't get a HTTP 500 error. Check your file and folder permissions:

Files: `0644`
Directories: `0755`

I don't know which OS you have, but with UNIX systems you can run the following commands on your terminal:

```shell
cd <PHPBB_ROOT>/ext/alfredoramos/simplespoiler
find . -type f -exec chmod 0644 {} \;
find . -type d -exec chmod 0755 {} \;
```

**Comment by recon88** [comment]
Permissions are fine as well. The said ones are applied as soon as I upload files/folders.
I guess I have to give up on that one because it could be literally everything as you said :/
