### ISSUE TITLE
Doesn't work in Chrome on Android

### ISSUE THREAD

**Issue by ConeRX** [AlfredoRamos/phpbb-ext-simple-spoiler#4]
Hi again,
the extension doesn't work when the forum is accessed via Chrome or the default browser on Android as new as Android 6.0. Nothing happens when the show button is pressed. However it works perfectly with Firefox on Android and the desktop version of Chrome.

**Comment by AlfredoRamos** [comment]
Can you test if the spoiler in this topic works for you? https://goo.gl/G25y4d

It will help to check if another extension is in conflict with the spoiler plugin.

Can you provide your board URL to check?

**Comment by ConeRX** [comment]
Sorry, I was busy the last few days.
I checked it again and it works with the current version. I was accidentally running an outdated version (1.0.2).
