### ISSUE TITLE
Don't show at ACP

### ISSUE THREAD

**Issue by ongewoongio** [AlfredoRamos/phpbb-ext-simple-spoiler#5]
Hey,

When I installed at root/ext/ it doesn't come up at the ACP

**Comment by AlfredoRamos** [comment]
It does not need an ACP page

**Comment by ongewoongio** [comment]
It doesn't show at the BBcodes aswell.

**Comment by AlfredoRamos** [comment]
Did it throw an error when you enabled the extension? do you have another similar extension installed?

I need more info:

- Web server and its version (Apache, Nginx, etc)
- PHP version
- DBMS and its version (MySQL, MariaDB, etc)
- phpBB version

**Comment by ongewoongio** [comment]
Web server: Apache/2
PHP version 7.1
10.1.24-MariaDB - MariaDB Serve
phpBB 3.2.1

**Comment by AlfredoRamos** [comment]
> Did it throw an error when you enabled the extension? do you have another similar extension installed?

What's your board URL?

**Comment by AlfredoRamos** [comment]
> It doesn't show at the BBcodes aswell

I think you mean in the editor, right?

In your ACP go to `Posting` tab > `BBCodes` click on `Edit` (green gear) and check `Display on posting`

**Comment by ongewoongio** [comment]
No error at all, only other extension I installed is  phpBB Media Embed PlugIn

Url to the board: http://forum.teletubbiegame.nl/index.php

**Comment by AlfredoRamos** [comment]
It seems that the extension is not installed correctly or disabled, CSS nor JS files exists in the extension path.

http://forum.teletubbiegame.nl/ext/alfredoramos/simplespoiler/styles/all/theme/js/spoiler.js

Please run this SQL query and post its result:

```sql
SELECT bbcode_id, bbcode_tag FROM phpbb_bbcodes WHERE bbcode_tag LIKE '%spoiler%';
```

**Comment by ongewoongio** [comment]
Hm, I don't know what I've changed, but I see the green gear now.
Thank you anyway 👍

**Comment by AlfredoRamos** [comment]
It is enabled now, it should be working.
